name: Initialize-EC2

jobs:
  deploy:
    name: Initialize EC2 instance
    runs-on: ubuntu-latest
    steps:
      - name: executing deploy ssh command on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            git clone https://github.com/josinovmota/BotLivesDoctor.git
            chmod +x ~/BotLivesDoctor/aws/init.sh
            chmod +x ~/BotLivesDoctor/aws/deploy.sh
            ~/BotLivesDoctor/aws/init.sh
